### PR TITLE
Fix Name clash fix #134

### LINKED ISSUE #134: Disambiguate toChannel() name clash
The extension functions `ReadStream<T>.toChannel(vertx)` and `WriteStream<T>.toChannel(vertx)` (note the omission of the optional `capacity` parameter) are in a name clash for receiver classes that are both Read+Write streams (notably `AsyncFile`).

They can be disambiguated by, for instance, renaming them to `ReadStream<T>.toReceiveChannel(vertx: Vertx)` and `WriteStream<T>.toSendChannel(vertx: Vertx)`, respectively.

### PR DESCRIPTION
**Pull request by kostya05983**
Pr solves problem with name clash on AsyncFile.
Please see #134 
@vietj 
@gmariotti

### CODE REVIEW

File: vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/ReceiveChannelHandler.kt [hunk 1]
```diff
@@ -116,15 +116,29 @@ fun <T> Vertx.receiveChannelHandler(): ReceiveChannelHandler<T> = ReceiveChannel
  * @param vertx the related vertx instance
  * @param capacity the channel buffering capacity
  */
+@Deprecated("Please use toRecieveChannel instead to avoid name clash")
```
Comment (vietj) [inline vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/ReceiveChannelHandler.kt]: typo in doc : `toRecieveChannel`

Comment (kostya05983) [reply vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/ReceiveChannelHandler.kt]: thanks, fix it.

**Comment by kostya05983** [comment]
Hello, @vietj can you review my fixes?
