### PR TITLE
Coroutine to Vert.x Future with vertxFuture builder

### LINKED ISSUE #209: Provide a vertxFuture coroutine builder
#### Describe the feature

In addition to the [existing helper methods and builders](https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/), it would be useful to provide a coroutine builder that returns a `Future<T>`. 

**Example:**

```kotlin
// MyService is a service proxy.
class JokeServiceImpl: JokeService {
    override fun fetchJokes(): Future<JsonArray> = future {
        // Suspending methods can be used here to fetch the data.
        jsonArray()
    }
}

// Sub-par implementation; shouldn't actually be used.
fun <T> future(block: suspend () -> T) : Future<T> {
    val dispatcher = Vertx.currentContext().dispatcher()
    val promise = Promise.promse<T>()
    try {
        // Some magic to run this in a CoroutineScope / Vertx dispatcher.
        launch {
            promise.complete(block())
        }
    } catch (ex: Exception) {
        promise.fail(ex)
    }
    return promise.future
}
```

#### Use cases

Presently, writing code that bridges coroutines and future (e.g. service proxies) can be awkward. You need to create a `Promise`, launch a coroutine, and handle completion of the promise:

```kotlin
class JokeServiceImpl(private val vertx: Vertx) : JokeService {
    override fun fetchJokes(): Future<JsonArray> {
        val promise = Promise.promise<JsonArray>()

        launch {
            try {
               val jokes: JsonArray = TODO() // suspending code to fetch jokes
               promise.complete(jokes)
            } catch (ex: Exception) {
               promise.fail(ex)
            }
        }
        return promise.future
    }
}
```

The kotlin.coroutines project includes several helper functions similar to this.

For example:

* [Bridge a JDK 8 Future to a coroutine](
https://github.com/Kotlin/kotlinx.coroutines/blob/5e870c11311b3bfd58f0557c651f1d877e9e5827/integration/kotlinx-coroutines-jdk8/src/future/Future.kt#L34-L46)
    ```kotlin
    fun returnsFuture(): CompletableFuture<String> = future {
        delay(1_000) // run a coroutine
        "Hello"
    }
    ```
* [Bridge a reactor `mono` to a coroutine ](
https://github.com/Kotlin/kotlinx.coroutines/blob/5e870c11311b3bfd58f0557c651f1d877e9e5827/reactive/kotlinx-coroutines-reactor/src/Mono.kt#L17-L35)
    ```kotlin
    fun returnsMono(): Mono<String> = mono {
        delay(1_000) // run a coroutine
        "Hello"
    }
    ```

### PR DESCRIPTION
**Pull request by tsegismont**
Closes #209

### CODE REVIEW

File: vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/VertxCoroutine.kt [hunk 1]
```diff
@@ -268,3 +257,26 @@ private class VertxCoroutineExecutor(val vertxContext: Context) : AbstractExecut
     throw UnsupportedOperationException("should not be called")
   }
 }
+
+fun <T> vertxFuture(scope: CoroutineScope = GlobalScope, block: suspend CoroutineScope.() -> T): Future<T> {
+  val currentContext: Context? = Vertx.currentContext()
+  require(currentContext != null) { "Not running on Vert.x context" }
```
Comment (wowselim) [inline vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/VertxCoroutine.kt:263]:
```suggestion
  requireNotNull(currentContext) { "Not running on Vert.x context" }
```
